const ICONS = {
  profileIcon: require('../assets/img/ProfileIcon.png'),
  lockIcon: require('../assets/img/Lock.png'),
  emailIcon: require('../assets/img/Email.png'),
  plusIcon: require('../assets/img/PlusIcon.png'),
  addIcon: require('../assets/img/AddIcon.png'),
  deleteIcon: require('../assets/img/DeleteIcon.png'),
  calendarIcon: require('../assets/img/calendarIcon.png'),
  maleIcon: require('../assets/img/MaleIcon.png'),
  femaleIcon: require('../assets/img/FemaleIcon.png'),
  emailIconDetail: require('../assets/img/emailIcon.png'),
  phoneIcon: require('../assets/img/phoneIcon.png'),
  searchIconBlack: require('../assets/img/SearchIconBlack.png'),
  searchIconWhite: require('../assets/img/SearchIconWhite.png'),
  telegramIcon: require('../assets/img/telegramIcon.png'),
  docIcon: require('../assets/img/docIcon.png'),
  requestsIcon: require('../assets/img/requestsIcon.png'),
  helpIcon: require('../assets/img/helpIcon.png'),
  addPhotoIcon: require('../assets/img/addPhotoIcon.png'),
  dropDownIcon: require('../assets/img/DropDownIcon.png'),
  dropDownIconActive: require('../assets/img/DropDownIconActive.png'),
  dropDownIconWhite: require('../assets/img/DropDownIconWhite.png'),
  locationIcon: require('../assets/img/LocationIcon.png'),
  homeIcon: require('../assets/img/HomeIcon.png'),
  homeIconWhite: require('../assets/img/HomeIconWhite.png'),
  chatIcon: require('../assets/img/chatIcon.png'),
  chatIconWhite: require('../assets/img/chatIconWhite.png'),
  heartIcon: require('../assets/img/heartIcon.png'),
  heartIconRed: require('../assets/img/heartIconRed.png'),
  heartIconWhite: require('../assets/img/heartIconWhite.png'),
  filterIcon: require('../assets/img/filterIcon.png'),
  allGendersIcon: require('../assets/img/allGendersIcon.png'),
  sendIcon: require('../assets/img/sendIcon.png'),
  rusIcon: require('../assets/img/rusIcon.png'),
  gbrIcon: require('../assets/img/gbrIcon.png'),
  uaIcon: require('../assets/img/uaIcon.png'),
  eyeIcon: require('../assets/img/eyeIcon.png'),
  BlockIcon: require('../assets/img/BlockIcon.png'),
  ReportIcon: require('../assets/img/ReportIcon.png'),
  BackArrowIcon: require('../assets/img/BackArrowIcon.png'),
  BackArrowIconWhite: require('../assets/img/BackArrowIconWhite.png'),
  menuButtonWhiteIcon: require('../assets/img/menuButtonWhite.png'),
  belIcon: require('../assets/img/belIcon.png'),
  plIcon: require('../assets/img/plIcon.png'),
  dostIcon: require('../assets/img/dotsIcon.png'),
  chatBg: require('../assets/img/chatBG.jpg'),
  addPhotoThumb: require('../assets/img/addPhotoThumb.png'),
  deletePhotoIcon: require('../assets/img/deletePhotoIcon.png'),
  addPhotoIconWhite: require('../assets/img/addPhotoIconWhite.png'),
  closeIcon: require('../assets/img/closeIcon.png'),
  reportIconGray: require('../assets/img/reportIconGray.png'),
  anonymusIcon: require('../assets/img/anonymousIcon.png'),
  anonymusIconBlack: require('../assets/img/anonymousIconBlack.png'),
  closeIconWhite: require('../assets/img/closeIconWhite.png'),
  checkIconWhite: require('../assets/img/checkIconWhite.png'),
  matchIcon: require('../assets/img/matchIcon.png'),
  likeToMeIcon: require('../assets/img/likeToMeIcon.png'),
  likeFromMeIcon: require('../assets/img/likeFromMeIcon.png'),
  infoIcon: require('../assets/img/infoIcon.png'),
  reportIconWhite: require('../assets/img/reportIconWhite.png'),
  sponsorIcon: require('../assets/img/SponsorIcon.png'),
  keepterIcon: require('../assets/img/KeepterIcon.png'),
  gerIcon: require('../assets/img/gerIcon.png'),
  itlIcon: require('../assets/img/itlIcon.png'),
  spaIcon: require('../assets/img/spaIcon.png'),
  fraIcon: require('../assets/img/fraIcon.png'),
  porIcon: require('../assets/img/porIcon.png'),
  guestsIcon: require('../assets/img/GuestsIcon.png'),
  copyIcon: require('../assets/img/copyIcon.png'),
  editIcon: require('../assets/img/editIcon.png'),
  publicChatIcon: require('../assets/img/publicChatIcon.png'),
  goals: {
    family: require('../assets/img/goals/family.png'),
    familyActive: require('../assets/img/goals/familyActive.png'),
    tarvels: require('../assets/img/goals/travels.png'),
    travelsActive: require('../assets/img/goals/travelsActive.png'),
    flirt: require('../assets/img/goals/flirt.png'),
    flirtActive: require('../assets/img/goals/flirtActive.png'),
    chat: require('../assets/img/goals/chat.png'),
    chatActive: require('../assets/img/goals/chatActive.png'),
    friendship: require('../assets/img/goals/friendship.png'),
    friendshipActive: require('../assets/img/goals/friendshipActive.png'),
    sex: require('../assets/img/goals/sex.png'),
    sexActive: require('../assets/img/goals/sexActive.png'),
  },
  goalsArray: [
    require('../assets/img/goals/family.png'),
    require('../assets/img/goals/travels.png'),
    require('../assets/img/goals/flirt.png'),
    require('../assets/img/goals/chat.png'),
    require('../assets/img/goals/friendship.png'),
    require('../assets/img/goals/sex.png'),
  ],
  genders: {
    male: require('../assets/img/genders/male.png'),
    maleActive: require('../assets/img/genders/maleActive.png'),
    female: require('../assets/img/genders/female.png'),
    femaleActive: require('../assets/img/genders/femaleActive.png'),
  },
  alco: {
    noAlco: require('../assets/img/alco/noAlco.png'),
    noAlcoActive: require('../assets/img/alco/noAlcoActive.png'),
    smalAlco: require('../assets/img/alco/smalAlco.png'),
    smalAlcoActive: require('../assets/img/alco/smalAlcoActive.png'),
    mediumAlco: require('../assets/img/alco/mediumAlco.png'),
    mediumAlcoActive: require('../assets/img/alco/mediumAlcoActive.png'),
    manyAlco: require('../assets/img/alco/manyAlco.png'),
    manyAlcoActive: require('../assets/img/alco/manyAlcoActive.png'),
  },
  alcoArray: [
    require('../assets/img/alco/noAlco.png'),
    require('../assets/img/alco/smalAlco.png'),
    require('../assets/img/alco/mediumAlco.png'),
    require('../assets/img/alco/manyAlco.png'),
  ],
  kids: {
    haveChild: require('../assets/img/kids/haveChild.png'),
    haveChildActive: require('../assets/img/kids/haveChildActive.png'),
    liveSeparetly: require('../assets/img/kids/liveSeparetly.png'),
    liveSeparetlyActive: require('../assets/img/kids/liveSeparetlyActive.png'),
    noChild: require('../assets/img/kids/noChild.png'),
    noChildActive: require('../assets/img/kids/noChildActive.png'),
    planChildren: require('../assets/img/kids/planChildren.png'),
    planChildrenActive: require('../assets/img/kids/planChildrenActive.png'),
  },
  kidsArray: [
    require('../assets/img/kids/noChild.png'),
    require('../assets/img/kids/planChildren.png'),
    require('../assets/img/kids/haveChild.png'),
    require('../assets/img/kids/liveSeparetly.png'),
  ],
  smoking: {
    noSmoking: require('../assets/img/smoking/noSmoking.png'),
    noSmokingActive: require('../assets/img/smoking/noSmokingActive.png'),
    smalSmoking: require('../assets/img/smoking/smalSmoking.png'),
    smalSmokingActive: require('../assets/img/smoking/smalSmokingActive.png'),
    mediumSmoking: require('../assets/img/smoking/mediumSmoking.png'),
    mediumSmokingActive: require('../assets/img/smoking/mediumSmokingActive.png'),
    manySmoking: require('../assets/img/smoking/manySmoking.png'),
    manySmokingActive: require('../assets/img/smoking/manySmokingActive.png'),
  },
  smokingArray: [
    require('../assets/img/smoking/noSmoking.png'),
    require('../assets/img/smoking/smalSmoking.png'),
    require('../assets/img/smoking/mediumSmoking.png'),
    require('../assets/img/smoking/manySmoking.png'),
  ],
};

export {ICONS};
